### ISSUE TITLE
Add QuiltGoSlightlyFasterLol

### ISSUE THREAD

**Issue by otter501** [intergrav/Adrenaline#13]
It makes quilt go slightly faster, all optimization matters 

[https://modrinth.com/mod/quiltgoslighlyfasterlol](https://modrinth.com/mod/quiltgoslighlyfasterlol)

**Comment by HyperSoop** [comment]
Why

**Comment by intergrav** [comment]
the mod barely makes an improvement and in itself *is* a joke (i mean, telling by the mod name, icon, and what it actually does)
