### ISSUE TITLE
Add Iris

### ISSUE THREAD

**Issue by obj-obj** [intergrav/adrenaline#14]
Iris has entity rendering optimizations that apply even when shaders are disabled

**Comment by intergrav** [comment]
Iris tends to give a *very* small improvement (or even make performance worse) while ImmediatelyFast is present, so this will likely not be added as I'd prefer not to have shaderpack features in Adrenaline by default

**Comment by obj-obj** [comment]
> Iris tends to give a _very_ small improvement (or even make performance worse) while ImmediatelyFast is present, so this will likely not be added as I'd prefer not to have shaderpack features in Adrenaline by default. Thanks for the suggestion though.
> 
> If you have any benchmarks that could contest this, feel free to show me, but I don't think I'll add it either way unless it improves performance a lot

Don’t ImmediatelyFast’s benchmarks show iris being ~2x faster than just sodium?

**Comment by intergrav** [comment]
ImmediatelyFast's benchmarks shows that `IF + Sodium` is slightly faster than `IF + Sodium + Iris`. 
Iris *can* heavily improve performance when ImmediatelyFast isn't present, but when IF is present, Iris doesn't impact it at all.

**Comment by Gaming32** [comment]
Yeah, the slight optimization that Iris gives is also present in InmediatelyFast, which has other optimizations as well.

**Comment by obj-obj** [comment]
> Yeah, the slight optimization that Iris gives is also present in InmediatelyFast, which has other optimizations as well.

Ah, makes sense
