### ISSUE TITLE
Remove Memory Leak Fix

### ISSUE THREAD

**Issue by Gaming32** [intergrav/adrenaline#17]
It can cause various issues. For instance, https://github.com/fxmorin/MemoryLeakFix/issues/120.

**Comment by intergrav** [comment]
yeah, it's also pretty redundant anyway so I'll remove it next update

**Comment by MenacingPerson** [comment]
Really? Can I know why it's redundant? Is there another mod that applies the same fixes? I know ModernFix applies 1 fix for memory leaks.

**Comment by intergrav** [comment]
actually - it's not very redundant, i'm unsure why I said that, but i agree with what gaming32 had said. i've seen a few other issues in the past aswell
