### ISSUE TITLE
Add Noxesium

### ISSUE THREAD

**Issue by MenacingPerson** [intergrav/adrenaline#18]
https://modrinth.com/mod/noxesium

It's made for MCC Island but works on everything.

Highlights:

Bugfixes

    Always display head layer in TAB menu
    Change teleport packets to teleport vehicle passengers to their vehicle
    Fixes lighting issues with moving piston walls
    Fixes custom models sometimes disappearing when not looking at the center

**Comment by intergrav** [comment]
I feel like Noxesium is out of scope for Adrenaline, it's bug fixes and performance features are too small and specific for it to be included as a whole extra mod in the pack. 
Based on their GitHub repository, the only performance feature it seems to have is this:
> Optimized Beacon block entity rendering (disabled when using Iris Shaders)
