### ISSUE TITLE
Overwrites options.txt

### ISSUE THREAD

**Issue by TheNicestDev** [intergrav/adrenaline#22]
When you install the modpack, all existing settings in the options.txt file will be overwritten and thus deleted
![image](https://cdn.discordapp.com/attachments/1073015038966767656/1117802287994249236/image.png)

**Comment by Gaming32** [comment]
It also overwrites all configs for mods in the pack. This is due to the absence of [YOSBR](https://modrinth.com/mod/yosbr).

**Comment by intergrav** [comment]
Will be kept in mind next time I update Adrenaline
