### ISSUE TITLE
Remove Smooth Boot for 1.19.4+

### ISSUE THREAD

**Issue by toooonyy** [intergrav/adrenaline#23]
<img width="873" alt="Screen Shot 2023-06-24 at 12 41 00" src="https://github.com/intergrav/adrenaline/assets/3480434/98d78804-00be-4de5-b009-729857b7134e">
Self-explaining.

**Comment by intergrav** [comment]
While the main functionality of the mod was fixed by mojang, it still allows you to adjust thread priorities which can make an impact on certain systems. See the latest issues on the issue tracker for more information

**Comment by toooonyy** [comment]
> While the main functionality of the mod was fixed by mojang, it still allows you to adjust thread priorities which can make an impact on certain systems. See the latest issues on the issue tracker for more information

thanks for the info.
